export const physiqueState = {
  level: 1,
  exp: 0,
  expMax: 100,
  stamina: 100,
  maxStamina: 100,
  passiveXpGained: 0,
  trainingSession: false,
  timingActive: false,
  sessionStamina: 0,
  sessionHits: 0,
  sessionXP: 0,
  cursorPosition: 0,
  cursorDirection: 1,
  cursorSpeed: 0,
  perfectHits: 0,
  hitStreak: 0,
};
