import { ACCURACY_BASE, DODGE_BASE } from '../combat/hit.js';
export const progressionState = {
  qi: 100,
  qiCapMult: 0,
  qiRegenMult: 0,
  foundation: 0,
  realm: { tier: 0, stage: 1 },
  cultivation: {
    talent: 1.0,
    foundationMult: 1.0,
    pillMult: 1.0,
    buildingMult: 1.0,
  },
  laws: {
    selected: null,
    unlocked: [],
    points: 0,
    trees: {
      sword: {},
      formation: {},
      alchemy: {},
    },
  },
  atkBase: 5,
  tempAtk: 0,
  tempArmor: 0,
    alchemy: { successBonus: 0 },
  karma: { qiRegen: 0, atk: 0, armor: 0 },
  pills: { ward: 0, meridian_opening_dan: 0 },
  breakthroughBonus: 0,
  breakthroughChanceMult: 1,
  attributes: {
    physique: 10,
    mind: 10,
    agility: 10,
    comprehension: 10,
    criticalChance: 0.05,
    attackSpeed: 1.0,
    cooldownReduction: 0,
    adventureSpeed: 1.0,
  },
  derivedStats: {
    armor: 0,
    accuracy: ACCURACY_BASE,
    dodge: DODGE_BASE,
  },
};
